name: H.G.Bespoke
favicon: null
layout_spectrum: 0.955656360834837
typography_spectrum: 0.43368
title: H.G.Bespoke.
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#dba358'
    - '#f7fcdc'
    - '#667161'
    - '#d6d2c6'
    - '#141319'
  brandStrength: 0
  lightness: 0.9085520850494504
  saturation: 0.125
  rhythmicContrast: 0.5
purpose: []
