name: H.G.Bespoke
favicon: null
layout_spectrum: 0.955656360834837
typography_spectrum: 0.60402
title: H.G.Bespoke.
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e9eae5'
    - '#c85a25'
    - '#e19742'
    - '#191317'
    - '#6b6c67'
  brandStrength: 0.1875
  lightness: 0.9085520850494504
  saturation: 0.125
  rhythmicContrast: 0.29695407929830253
purpose: []
